package cn.krly.platform.api.payment.pojo;

import java.io.Serializable;

public class AliPayConfig implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_config.id
     *
     * @mbggenerated Fri Apr 27 17:16:16 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_config.project_id
     *
     * @mbggenerated Fri Apr 27 17:16:16 CST 2018
     */
    private Integer projectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_config.app_id
     *
     * @mbggenerated Fri Apr 27 17:16:16 CST 2018
     */
    private String appId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_config.app_private_key
     *
     * @mbggenerated Fri Apr 27 17:16:16 CST 2018
     */
    private String appPrivateKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_config.app_public_key
     *
     * @mbggenerated Fri Apr 27 17:16:16 CST 2018
     */
    private String appPublicKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_config.return_url
     *
     * @mbggenerated Fri Apr 27 17:16:16 CST 2018
     */
    private String returnUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_config.notify_url
     *
     * @mbggenerated Fri Apr 27 17:16:16 CST 2018
     */
    private String notifyUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_config.gateway
     *
     * @mbggenerated Fri Apr 27 17:16:16 CST 2018
     */
    private String gateway;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_config.description
     *
     * @mbggenerated Fri Apr 27 17:16:16 CST 2018
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_config.id
     *
     * @return the value of alipay_config.id
     *
     * @mbggenerated Fri Apr 27 17:16:16 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_config.id
     *
     * @param id the value for alipay_config.id
     *
     * @mbggenerated Fri Apr 27 17:16:16 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_config.project_id
     *
     * @return the value of alipay_config.project_id
     *
     * @mbggenerated Fri Apr 27 17:16:16 CST 2018
     */
    public Integer getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_config.project_id
     *
     * @param projectId the value for alipay_config.project_id
     *
     * @mbggenerated Fri Apr 27 17:16:16 CST 2018
     */
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_config.app_id
     *
     * @return the value of alipay_config.app_id
     *
     * @mbggenerated Fri Apr 27 17:16:16 CST 2018
     */
    public String getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_config.app_id
     *
     * @param appId the value for alipay_config.app_id
     *
     * @mbggenerated Fri Apr 27 17:16:16 CST 2018
     */
    public void setAppId(String appId) {
        this.appId = appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_config.app_private_key
     *
     * @return the value of alipay_config.app_private_key
     *
     * @mbggenerated Fri Apr 27 17:16:16 CST 2018
     */
    public String getAppPrivateKey() {
        return appPrivateKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_config.app_private_key
     *
     * @param appPrivateKey the value for alipay_config.app_private_key
     *
     * @mbggenerated Fri Apr 27 17:16:16 CST 2018
     */
    public void setAppPrivateKey(String appPrivateKey) {
        this.appPrivateKey = appPrivateKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_config.app_public_key
     *
     * @return the value of alipay_config.app_public_key
     *
     * @mbggenerated Fri Apr 27 17:16:16 CST 2018
     */
    public String getAppPublicKey() {
        return appPublicKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_config.app_public_key
     *
     * @param appPublicKey the value for alipay_config.app_public_key
     *
     * @mbggenerated Fri Apr 27 17:16:16 CST 2018
     */
    public void setAppPublicKey(String appPublicKey) {
        this.appPublicKey = appPublicKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_config.return_url
     *
     * @return the value of alipay_config.return_url
     *
     * @mbggenerated Fri Apr 27 17:16:16 CST 2018
     */
    public String getReturnUrl() {
        return returnUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_config.return_url
     *
     * @param returnUrl the value for alipay_config.return_url
     *
     * @mbggenerated Fri Apr 27 17:16:16 CST 2018
     */
    public void setReturnUrl(String returnUrl) {
        this.returnUrl = returnUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_config.notify_url
     *
     * @return the value of alipay_config.notify_url
     *
     * @mbggenerated Fri Apr 27 17:16:16 CST 2018
     */
    public String getNotifyUrl() {
        return notifyUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_config.notify_url
     *
     * @param notifyUrl the value for alipay_config.notify_url
     *
     * @mbggenerated Fri Apr 27 17:16:16 CST 2018
     */
    public void setNotifyUrl(String notifyUrl) {
        this.notifyUrl = notifyUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_config.gateway
     *
     * @return the value of alipay_config.gateway
     *
     * @mbggenerated Fri Apr 27 17:16:16 CST 2018
     */
    public String getGateway() {
        return gateway;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_config.gateway
     *
     * @param gateway the value for alipay_config.gateway
     *
     * @mbggenerated Fri Apr 27 17:16:16 CST 2018
     */
    public void setGateway(String gateway) {
        this.gateway = gateway;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_config.description
     *
     * @return the value of alipay_config.description
     *
     * @mbggenerated Fri Apr 27 17:16:16 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_config.description
     *
     * @param description the value for alipay_config.description
     *
     * @mbggenerated Fri Apr 27 17:16:16 CST 2018
     */
    public void setDescription(String description) {
        this.description = description;
    }
}