package cn.krly.platform.api.payment.pojo;

import java.io.Serializable;

public class WxPayConfig implements Serializable {
    public static final int TYPE_H5 = 1;
    public static final int TYPE_APP = 2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxpay_config.id
     *
     * @mbggenerated Sat Apr 28 13:39:42 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxpay_config.project_id
     *
     * @mbggenerated Sat Apr 28 13:39:42 CST 2018
     */
    private Integer projectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxpay_config.app_id
     *
     * @mbggenerated Sat Apr 28 13:39:42 CST 2018
     */
    private String appId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxpay_config.app_key
     *
     * @mbggenerated Sat Apr 28 13:39:42 CST 2018
     */
    private String appKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxpay_config.mch_id
     *
     * @mbggenerated Sat Apr 28 13:39:42 CST 2018
     */
    private String mchId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxpay_config.notify_url
     *
     * @mbggenerated Sat Apr 28 13:39:42 CST 2018
     */
    private String notifyUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxpay_config.description
     *
     * @mbggenerated Sat Apr 28 13:39:42 CST 2018
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxpay_config.type
     *
     * @mbggenerated Sat Apr 28 13:39:42 CST 2018
     */
    private Integer type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxpay_config.id
     *
     * @return the value of wxpay_config.id
     *
     * @mbggenerated Sat Apr 28 13:39:42 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxpay_config.id
     *
     * @param id the value for wxpay_config.id
     *
     * @mbggenerated Sat Apr 28 13:39:42 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxpay_config.project_id
     *
     * @return the value of wxpay_config.project_id
     *
     * @mbggenerated Sat Apr 28 13:39:42 CST 2018
     */
    public Integer getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxpay_config.project_id
     *
     * @param projectId the value for wxpay_config.project_id
     *
     * @mbggenerated Sat Apr 28 13:39:42 CST 2018
     */
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxpay_config.app_id
     *
     * @return the value of wxpay_config.app_id
     *
     * @mbggenerated Sat Apr 28 13:39:42 CST 2018
     */
    public String getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxpay_config.app_id
     *
     * @param appId the value for wxpay_config.app_id
     *
     * @mbggenerated Sat Apr 28 13:39:42 CST 2018
     */
    public void setAppId(String appId) {
        this.appId = appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxpay_config.app_key
     *
     * @return the value of wxpay_config.app_key
     *
     * @mbggenerated Sat Apr 28 13:39:42 CST 2018
     */
    public String getAppKey() {
        return appKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxpay_config.app_key
     *
     * @param appKey the value for wxpay_config.app_key
     *
     * @mbggenerated Sat Apr 28 13:39:42 CST 2018
     */
    public void setAppKey(String appKey) {
        this.appKey = appKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxpay_config.mch_id
     *
     * @return the value of wxpay_config.mch_id
     *
     * @mbggenerated Sat Apr 28 13:39:42 CST 2018
     */
    public String getMchId() {
        return mchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxpay_config.mch_id
     *
     * @param mchId the value for wxpay_config.mch_id
     *
     * @mbggenerated Sat Apr 28 13:39:42 CST 2018
     */
    public void setMchId(String mchId) {
        this.mchId = mchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxpay_config.notify_url
     *
     * @return the value of wxpay_config.notify_url
     *
     * @mbggenerated Sat Apr 28 13:39:42 CST 2018
     */
    public String getNotifyUrl() {
        return notifyUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxpay_config.notify_url
     *
     * @param notifyUrl the value for wxpay_config.notify_url
     *
     * @mbggenerated Sat Apr 28 13:39:42 CST 2018
     */
    public void setNotifyUrl(String notifyUrl) {
        this.notifyUrl = notifyUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxpay_config.description
     *
     * @return the value of wxpay_config.description
     *
     * @mbggenerated Sat Apr 28 13:39:42 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxpay_config.description
     *
     * @param description the value for wxpay_config.description
     *
     * @mbggenerated Sat Apr 28 13:39:42 CST 2018
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxpay_config.type
     *
     * @return the value of wxpay_config.type
     *
     * @mbggenerated Sat Apr 28 13:39:42 CST 2018
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxpay_config.type
     *
     * @param type the value for wxpay_config.type
     *
     * @mbggenerated Sat Apr 28 13:39:42 CST 2018
     */
    public void setType(Integer type) {
        this.type = type;
    }
}