package com.krly.project.batterymanagement.db.mapper;

import com.krly.project.batterymanagement.db.entity.BatteryContainer;

public interface BatteryContainerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_battery_container
     *
     * @mbggenerated Mon May 21 15:15:15 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_battery_container
     *
     * @mbggenerated Mon May 21 15:15:15 CST 2018
     */
    int insert(BatteryContainer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_battery_container
     *
     * @mbggenerated Mon May 21 15:15:15 CST 2018
     */
    int insertSelective(BatteryContainer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_battery_container
     *
     * @mbggenerated Mon May 21 15:15:15 CST 2018
     */
    BatteryContainer selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_battery_container
     *
     * @mbggenerated Mon May 21 15:15:15 CST 2018
     */
    int updateByPrimaryKeySelective(BatteryContainer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_battery_container
     *
     * @mbggenerated Mon May 21 15:15:15 CST 2018
     */
    int updateByPrimaryKey(BatteryContainer record);
}