package com.krly.project.batterymanagement.db.mapper;

import com.krly.project.batterymanagement.db.entity.Battery;

public interface BatteryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_battery
     *
     * @mbggenerated Mon May 21 15:43:31 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_battery
     *
     * @mbggenerated Mon May 21 15:43:31 CST 2018
     */
    int insert(Battery record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_battery
     *
     * @mbggenerated Mon May 21 15:43:31 CST 2018
     */
    int insertSelective(Battery record);
}