package cn.krly.service.payment.mapper;

import cn.krly.platform.api.payment.pojo.WxPayConfig;

public interface WxPayConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxpay_config
     *
     * @mbggenerated Sat Apr 28 13:38:41 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxpay_config
     *
     * @mbggenerated Sat Apr 28 13:38:41 CST 2018
     */
    int insert(WxPayConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxpay_config
     *
     * @mbggenerated Sat Apr 28 13:38:41 CST 2018
     */
    int insertSelective(WxPayConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxpay_config
     *
     * @mbggenerated Sat Apr 28 13:38:41 CST 2018
     */
    WxPayConfig selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxpay_config
     *
     * @mbggenerated Sat Apr 28 13:38:41 CST 2018
     */
    int updateByPrimaryKeySelective(WxPayConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxpay_config
     *
     * @mbggenerated Sat Apr 28 13:38:41 CST 2018
     */
    int updateByPrimaryKey(WxPayConfig record);

    WxPayConfig getWxPayConfigOfProject(int projectId, int type);
    WxPayConfig getWxPayConfigByAppId(String appId);
    int delete(int projectId, int type);
}