package com.krly.project.batterymanagement.db.entity;

public class BatteryContainer {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_battery_container.id
     *
     * @mbggenerated Mon May 21 15:15:15 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_battery_container.IMEI
     *
     * @mbggenerated Mon May 21 15:15:15 CST 2018
     */
    private String imei;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_battery_container.ICCID
     *
     * @mbggenerated Mon May 21 15:15:15 CST 2018
     */
    private String iccid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_battery_container.mac
     *
     * @mbggenerated Mon May 21 15:15:15 CST 2018
     */
    private String mac;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_battery_container.longitude
     *
     * @mbggenerated Mon May 21 15:15:15 CST 2018
     */
    private Float longitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_battery_container.latitude
     *
     * @mbggenerated Mon May 21 15:15:15 CST 2018
     */
    private Float latitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_battery_container.geohash
     *
     * @mbggenerated Mon May 21 15:15:15 CST 2018
     */
    private String geohash;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_battery_container.status
     *
     * @mbggenerated Mon May 21 15:15:15 CST 2018
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_battery_container.id
     *
     * @return the value of tbl_battery_container.id
     *
     * @mbggenerated Mon May 21 15:15:15 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_battery_container.id
     *
     * @param id the value for tbl_battery_container.id
     *
     * @mbggenerated Mon May 21 15:15:15 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_battery_container.IMEI
     *
     * @return the value of tbl_battery_container.IMEI
     *
     * @mbggenerated Mon May 21 15:15:15 CST 2018
     */
    public String getImei() {
        return imei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_battery_container.IMEI
     *
     * @param imei the value for tbl_battery_container.IMEI
     *
     * @mbggenerated Mon May 21 15:15:15 CST 2018
     */
    public void setImei(String imei) {
        this.imei = imei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_battery_container.ICCID
     *
     * @return the value of tbl_battery_container.ICCID
     *
     * @mbggenerated Mon May 21 15:15:15 CST 2018
     */
    public String getIccid() {
        return iccid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_battery_container.ICCID
     *
     * @param iccid the value for tbl_battery_container.ICCID
     *
     * @mbggenerated Mon May 21 15:15:15 CST 2018
     */
    public void setIccid(String iccid) {
        this.iccid = iccid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_battery_container.mac
     *
     * @return the value of tbl_battery_container.mac
     *
     * @mbggenerated Mon May 21 15:15:15 CST 2018
     */
    public String getMac() {
        return mac;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_battery_container.mac
     *
     * @param mac the value for tbl_battery_container.mac
     *
     * @mbggenerated Mon May 21 15:15:15 CST 2018
     */
    public void setMac(String mac) {
        this.mac = mac;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_battery_container.longitude
     *
     * @return the value of tbl_battery_container.longitude
     *
     * @mbggenerated Mon May 21 15:15:15 CST 2018
     */
    public Float getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_battery_container.longitude
     *
     * @param longitude the value for tbl_battery_container.longitude
     *
     * @mbggenerated Mon May 21 15:15:15 CST 2018
     */
    public void setLongitude(Float longitude) {
        this.longitude = longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_battery_container.latitude
     *
     * @return the value of tbl_battery_container.latitude
     *
     * @mbggenerated Mon May 21 15:15:15 CST 2018
     */
    public Float getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_battery_container.latitude
     *
     * @param latitude the value for tbl_battery_container.latitude
     *
     * @mbggenerated Mon May 21 15:15:15 CST 2018
     */
    public void setLatitude(Float latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_battery_container.geohash
     *
     * @return the value of tbl_battery_container.geohash
     *
     * @mbggenerated Mon May 21 15:15:15 CST 2018
     */
    public String getGeohash() {
        return geohash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_battery_container.geohash
     *
     * @param geohash the value for tbl_battery_container.geohash
     *
     * @mbggenerated Mon May 21 15:15:15 CST 2018
     */
    public void setGeohash(String geohash) {
        this.geohash = geohash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_battery_container.status
     *
     * @return the value of tbl_battery_container.status
     *
     * @mbggenerated Mon May 21 15:15:15 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_battery_container.status
     *
     * @param status the value for tbl_battery_container.status
     *
     * @mbggenerated Mon May 21 15:15:15 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}