package com.krly.project.batterymanagement.db.entity;

public class Battery {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_battery.id
     *
     * @mbggenerated Mon May 21 15:43:31 CST 2018
     */
    private Integer id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_battery.id
     *
     * @return the value of tbl_battery.id
     *
     * @mbggenerated Mon May 21 15:43:31 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_battery.id
     *
     * @param id the value for tbl_battery.id
     *
     * @mbggenerated Mon May 21 15:43:31 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }
}